workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ipa --release --export-method=ad-hoc
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - 2217570346@qq.com
